Threshold = 6
Period = "30s"
GenesisTime = 1590032610
TransitionTime = 0
GenesisSeed = "7653d86e0b5fe59da082f16991f951413156ecbeba2ddf5aab406ed26fe9d4ec"

[[Nodes]]
  Address = "drand.clabs.co:4444"
  Key = "915757fadcbab50aacac565d937d57d51b00ad777e6c8e5800238949867eb6c389ca779f542c59884ed0c851cde6261e"
  TLS = true
  Index = 0

[[Nodes]]
  Address = "drand.cloudflare.com:8080"
  Key = "9252037c5beb23a8e439837f65ebf692caa2b62504a7471e3728d3231397d7834c7e486376d5e79a336fb67bf722fe4b"
  TLS = true
  Index = 1

[[Nodes]]
  Address = "ln.soc1024.com:8888"
  Key = "93735e52feba8dba278fab32af527ed2a8065dc5dd2c0e4f6cc278e87a692c830910d0633098ff30d119210c4a4c361c"
  TLS = true
  Index = 2

[[Nodes]]
  Address = "drand.c4dt.org:1234"
  Key = "9541e3fd228386b5d95b9f66f3119f0e4d01ed1775f17d7b043a2cab9985a2aadb38c1fd228096845a556e00dc1ad6d6"
  TLS = true
  Index = 3

[[Nodes]]
  Address = "drand.zerobyte.io:8765"
  Key = "a2ef3370668ee3fa8953417d76e70aa6547aa9cf8ea378760df85c935f7b1d35674b9978798961700c9e0c9f5c7e1914"
  TLS = true
  Index = 4

[[Nodes]]
  Address = "drand.lbarman.ch:443"
  Key = "a535e8d4432385782021f030dbd537ce7d9e0ec19b4a7f26567ab49dddf16e3c4ee8268f723071f70fd7ebe2035583f0"
  TLS = true
  Index = 5

[[Nodes]]
  Address = "drand.cothority.net:4444"
  Key = "a965616366f50cafbbe67bd2cc9217ea7354e3c3c93c0e90abf398382d494b7a6e716bc539c9b7314c2a068976cef753"
  TLS = true
  Index = 6

[[Nodes]]
  Address = "drand.nikkolasg.xyz:4444"
  Key = "aaac5d3b14a3e05728a763212d42f6dff162b87996ca8911bb03b74f2231c18434be92e8cd01b2c6c265cf3eb857b590"
  TLS = true
  Index = 7

[[Nodes]]
  Address = "drand2.kudelskisecurity.com:443"
  Key = "afac818dfd20e1c203dc0937ee4242a4a20217f705e2bb4c5a57285f05d4f3a05396319189f470f1c0fc519b2bd92c9a"
  TLS = true
  Index = 8

[[Nodes]]
  Address = "drand.protocol.ai:8080"
  Key = "b24b100d37dff1163e8813506bdd375f2baf8c38043cb2cabdbd1e063f68bab36aab74e830fd0ee054641da0fff8fd59"
  TLS = true
  Index = 9

[PublicKey]
  Coefficients = ["a8870f795c74ec1c36bf629810db22fcdc4d5a30dba79009d24cbc319ff33ca11377f1056f4f976c5f3659aa0ba2c189", "852a50fc3d5a58e660aac26c4599bd84ceb7db074e581b27ace2bd29460f8aac28d86e49d6ff559fee8db2091bd74f6a", "b52fa2566541fab2ce827ab680761add2b80805d8f0bfb98070550506193154fba0b2262e6e101490b3c000828ae0d31", "a1d2ef69ec7c4afe624e31a4ec61a155d990cf79244064e8a7026201d6883080d9c03d0be7376b3ef45b4a924c6399ac", "8f5eb57d6186b84e72876a62875a60d8ef040c89dbe1f62891fdd810f8a672d62f37adbfa008b94b069a377751bfe17c", "a019e2243129a862fba345cff0d8600da7c1277de918ea99504673d1a580cd86ada249cc89e2f97ddea283229e13f998"]
